# Generated by Django 3.1.14 on 2023-09-15 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(default='000-00-0000', max_length=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 16, 15, 45, 219801, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 16, 15, 45, 220247, tzinfo=utc), verbose_name='date due'),
        ),
    ]
