# Generated by Django 3.2.21 on 2023-09-15 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 19, 57, 50, 82772, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 19, 57, 50, 83151, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
    ]
