# Generated by Django 5.1.2 on 2024-10-31 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0004_auto_20241030_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 21, 36, 1, 448801, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 21, 36, 1, 450184, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
    ]
