# Generated by Django 2.1.1 on 2018-09-25 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0042_auto_20180913_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 17, 22, 4, 812318, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 17, 22, 4, 813245, tzinfo=utc), verbose_name='date due'),
        ),
    ]
